### ISSUE TITLE
Add compiled release

### ISSUE THREAD

**Issue by Keith94** [UCyborg/LegacyD3DResolutionHack#1]
Can you add a compiled DLL to the [releases page](https://github.com/UCyborg/LegacyD3DResolutionHack/releases)?

It may be included with the Drakan patch but it would be nice to have it separately for use in other games.

**Comment by UCyborg** [comment]
Agreed, added. Although the biggest issue here is that the it doesn't seem to work universally for every game, in some cases the library loading function is called with explicit path to the real library in Windows\System32, so our proxy library isn't picked up.

I think it would be a good idea if this code was part of some bigger ddraw wrapper project. I found out about DDrawCompat not too long ago.

I could probably still make another version of this based on ddraw.dll proxy that preloads d3dim DLLs and patches them. It would probably solve the problem I mentioned before.

I usually run Drakan with dgVoodoo DirectX Wrapper where this isn't needed since DX11 doesn't have such limitations. It's pretty good for modern systems with modern graphics cards, gives some FPS boost too and gets rid of that dreaded delay when alt-tabbing on Windows 8+ when game is in fullscreen mode.
