### ISSUE TITLE
How are these files supposed to be used?

### ISSUE THREAD

**Issue by Jakob900** [UCyborg/LegacyD3DResolutionHack#3]
Nevermind, figured it out

**Comment by UCyborg** [comment]
This is really just a prototype proof-of-concept implementation. It works with some games if you drop the DLLs in the game folder, but not all of them as in some cases, full path to the system version of those DLLs is used to load them. Games don't reference those DLLs directly, it's handled internally by DirectDraw.

The DLLs in this package should never be put in the System32/SysWOW64 directories as they're just proxies that eventually load the real DLLs in System32/SysWOW64.

I don't know what to think of regarding the fact that the other user got it to work with Harry Potter and the Chamber of Secrets and you can't. I don't have that game to test. 

The functionality of these DLLs is implemented in [DxWnd](https://sourceforge.net/projects/dxwnd/) and if you use that, it should work with all games. So give DxWnd a try and if you still have issues, ask about it [here](https://sourceforge.net/p/dxwnd/discussion/general/). Going from my memory, there is one tab in DxWnd's game profile settings window that lists a number of miscellaneous tweaks and one of them is called "LegacyD3DResolutionHack", so you can enable it there.

This project won't be updated any further due to availability of other feature-rich tools to tackle legacy DirectDraw/Direct3D issues.
